name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev pkg-config

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw --version 8.1.0
          choco install msys2
          msys2_shell.cmd -mingw64 -c "pacman -Syu --noconfirm"
          msys2_shell.cmd -mingw64 -c "pacman -S --noconfirm base-devel gcc"

      - name: Build for Linux
        if: runner.os == 'Linux'
        run: cargo tauri build

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: cargo build --target x86_64-pc-windows-gnu --release

      - name: Upload Linux Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: src-tauri/target/release/*

      - name: Upload Windows Artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: src-tauri/target/x86_64-pc-windows-gnu/release/*
