name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: rust-lang/rustup-action@v1
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y pkg-config

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: cargo tauri build

      - name: Set up MinGW for Windows
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v1
        with:
          packages: mingw-w64-x86_64-toolchain

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: cargo build --target x86_64-pc-windows-gnu --release

      - name: Upload Linux Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: target/release/*

      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: target/x86_64-pc-windows-gnu/release/*
